// <auto-generated />
using System;
using Measuring_equipment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Measuring_equipment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181115123051_DeviceMod")]
    partial class DeviceMod
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Measuring_equipment.Models.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CurrentlyInUse");

                    b.Property<string>("DeviceDesc");

                    b.Property<string>("InventoryNo");

                    b.Property<DateTime?>("ProductionDate");

                    b.Property<int>("RegistrationNo");

                    b.Property<string>("SerialNo");

                    b.Property<DateTime?>("TimeToVerification");

                    b.Property<int>("TypeId");

                    b.Property<DateTime?>("VerificationDate");

                    b.Property<string>("VerificationResult");

                    b.HasKey("DeviceId");

                    b.HasIndex("TypeId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Measuring_equipment.Models.Laboratory", b =>
                {
                    b.Property<int>("LaboratoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Accreditation");

                    b.Property<string>("LaboratoryDesc");

                    b.Property<string>("LaboratoryName");

                    b.HasKey("LaboratoryId");

                    b.ToTable("Laboratories");
                });

            modelBuilder.Entity("Measuring_equipment.Models.Producer", b =>
                {
                    b.Property<int>("ProducerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProducerDesc");

                    b.Property<string>("ProducerName");

                    b.HasKey("ProducerId");

                    b.ToTable("Producers");
                });

            modelBuilder.Entity("Measuring_equipment.Models.Type", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LaboratoriesLaboratoryId");

                    b.Property<decimal>("Price");

                    b.Property<int?>("ProducerId");

                    b.Property<string>("TypeDesc");

                    b.Property<string>("TypeName");

                    b.Property<int>("ValidityPierod");

                    b.HasKey("TypeId");

                    b.HasIndex("LaboratoriesLaboratoryId");

                    b.HasIndex("ProducerId");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("Measuring_equipment.Models.Device", b =>
                {
                    b.HasOne("Measuring_equipment.Models.Type", "Type")
                        .WithMany("Devices")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Measuring_equipment.Models.Type", b =>
                {
                    b.HasOne("Measuring_equipment.Models.Laboratory", "Laboratories")
                        .WithMany("Types")
                        .HasForeignKey("LaboratoriesLaboratoryId");

                    b.HasOne("Measuring_equipment.Models.Producer", "Producer")
                        .WithMany("Types")
                        .HasForeignKey("ProducerId");
                });
#pragma warning restore 612, 618
        }
    }
}
